# Generated by Django 6.0.5 on 2026-06-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_transaction_date_budget'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'verbose_name': 'بودجه', 'verbose_name_plural': 'Budgets'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='rating',
            field=models.CharField(blank=True, choices=[('bad', '👎 بد'), ('medium', '👍 متوسط'), ('good', '🌟 خوب')], max_length=6, null=True),
        ),
    ]
