# Generated by Django 6.0.5 on 2026-06-21 17:13

import django_jalali.db.models
import jdatetime
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_budget_options_transaction_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=django_jalali.db.models.jDateField(default=jdatetime.date.today),
        ),
    ]
